import type { IconType } from "react-icons";
import { FaAws } from "react-icons/fa6";
import { IoLogoFirebase } from "react-icons/io5";

import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiBootstrap,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiPython,
  SiPhp,
  SiMongodb,
  SiMongoose,
  SiPostgresql,
  SiDocker,
  SiGithubactions,
  SiKubernetes,
  SiVercel,
  SiRailway,
  SiGit,
  SiGithub,
  SiCloudinary,
  SiSocketdotio,
  SiJsonwebtokens,
  SiGoogle,
  SiNetlify,
  SiAppwrite,
  SiPostman,
  SiPrisma,
  SiSqlite,
} from "react-icons/si";
import {
  TbApi,
  TbSql,
  TbInfinity,
  TbCloudDataConnection,
  TbBroadcast,
  TbChartLine,
  TbTimeline,
  TbCode,
  TbBrandRedux,
  TbBrandMysql,
  TbBrandCpp,
} from "react-icons/tb";

const iconMap: Record<string, IconType> = {
  SiPrisma,
  SiSqlite,
  TbBrandCpp,
  TbBrandMysql,
  SiPostman,
  TbBrandRedux,
  SiNetlify,
  FaAws,
  IoLogoFirebase,
  SiAppwrite,
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiBootstrap,
  SiHtml5,
  SiCss,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiPython,
  SiPhp,
  SiMongodb,
  SiMongoose,
  SiPostgresql,
  SiDocker,
  SiGithubactions,
  SiKubernetes,
  SiVercel,
  SiRailway,
  SiGit,
  SiGithub,
  SiCloudinary,
  SiSocketdotio,
  SiJsonwebtokens,
  SiGoogle,
  TbApi,
  TbSql,
  TbInfinity,
  TbCloudDataConnection,
  TbBroadcast,
  TbChartLine,
  TbTimeline,
};
export function getIcon(name: string): IconType {
  return iconMap[name] ?? TbCode;
}
